# copilot help to find the fastest way to create and increment the database
import sqlite3

def connect_db():
    return sqlite3.connect('shapes.db')

def insert_data():
    conn = connect_db()
    cursor = conn.cursor()

    questions = [
        ('Which is the red circle?',),
        ('Which is the red heart?',),
        ('Which is the red semicircle?',),
        ('Which is the red diamond?',),
        ('Which is the red square?',),
        ('Which is the red star?',),
        ('Which is the red rectangle?',),
        ('Which is the red triangle?',),
        ('Which is the red oval?',),
        ('Which is the red pentagon?',),
        ('Which is the red hexagon?',),
        ('Which is the red rhombus?',),
        ('Which is the blue heart?',),
        ('Which is the blue circle?',),
        ('Which is the blue diamond?',),
        ('Which is the blue square?',),
        ('Which is the blue star?',),
        ('Which is the blue rectangle?',),
        ('Which is the blue triangle?',),
        ('Which is the blue oval?',),
        ('Which is the blue pentagon?',),
        ('Which is the blue hexagon?',),
        ('Which is the blue rhombus?',),
        ('Which is the blue semicircle?',),
        ('Which is the gray heart?',),
        ('Which is the gray circle?',),
        ('Which is the gray diamond?',),
        ('Which is the gray square?',),
        ('Which is the gray star?',),
        ('Which is the gray rectangle?',),
        ('Which is the gray triangle?',),
        ('Which is the gray oval?',),
        ('Which is the gray pentagon?',),
        ('Which is the gray hexagon?',),
        ('Which is the gray rhombus?',),
        ('Which is the gray semicircle?',),
        ('Which is the pink heart?',),
        ('Which is the pink circle?',),
        ('Which is the pink diamond?',),
        ('Which is the pink square?',),
        ('Which is the pink star?',),
        ('Which is the pink rectangle?',),
        ('Which is the pink triangle?',),
        ('Which is the pink oval?',),
        ('Which is the pink pentagon?',),
        ('Which is the pink hexagon?',),
        ('Which is the pink rhombus?',),
        ('Which is the pink semicircle?',),
        ('Which is the white heart?',),
        ('Which is the white circle?',),
        ('Which is the white diamond?',),
        ('Which is the white square?',),
        ('Which is the white star?',),
        ('Which is the white rectangle?',),
        ('Which is the white triangle?',),
        ('Which is the white oval?',),
        ('Which is the white pentagon?',),
        ('Which is the white hexagon?',),
        ('Which is the white rhombus?',),
        ('Which is the white semicircle?',),
        ('Which is the yellow heart?',),
        ('Which is the yellow circle?',),
        ('Which is the yellow diamond?',),
        ('Which is the yellow square?',),
        ('Which is the yellow star?',),
        ('Which is the yellow rectangle?',),
        ('Which is the yellow triangle?',),
        ('Which is the yellow oval?',),
        ('Which is the yellow pentagon?',),
        ('Which is the yellow hexagon?',),
        ('Which is the yellow rhombus?',),
        ('Which is the yellow semicircle?',),
        ('Which is the green heart?',),
        ('Which is the green circle?',),
        ('Which is the green diamond?',),
        ('Which is the green square?',),
        ('Which is the green star?',),
        ('Which is the green rectangle?',),
        ('Which is the green triangle?',),
        ('Which is the green oval?',),
        ('Which is the green pentagon?',),
        ('Which is the green hexagon?',),
        ('Which is the green rhombus?',),
        ('Which is the green semicircle?',),
        ('Which is the orange heart?',),
        ('Which is the orange circle?',),
        ('Which is the orange diamond?',),
        ('Which is the orange square?',),
        ('Which is the orange star?',),
        ('Which is the orange rectangle?',),
        ('Which is the orange triangle?',),
        ('Which is the orange oval?',),
        ('Which is the orange pentagon?',),
        ('Which is the orange hexagon?',),
        ('Which is the orange rhombus?',),
        ('Which is the orange semicircle?',),
        ('Which is the purple heart?',),
        ('Which is the purple circle?',),
        ('Which is the purple diamond?',),
        ('Which is the purple square?',),
        ('Which is the purple star?',),
        ('Which is the purple rectangle?',),
        ('Which is the purple triangle?',),
        ('Which is the purple oval?',),
        ('Which is the purple pentagon?',),
        ('Which is the purple hexagon?',),
        ('Which is the purple rhombus?',),
        ('Which is the purple semicircle?',),
        ('Which is the black heart?',),
        ('Which is the black circle?',),
        ('Which is the black diamond?',),
        ('Which is the black square?',),
        ('Which is the black star?',),
        ('Which is the black rectangle?',),
        ('Which is the black triangle?',),
        ('Which is the black oval?',),
        ('Which is the black pentagon?',),
        ('Which is the black hexagon?',),
        ('Which is the black rhombus?',),
        ('Which is the black semicircle?',),
        ('Which is the brown heart?',),
        ('Which is the brown circle?',),
        ('Which is the brown diamond?',),
        ('Which is the brown square?',),
        ('Which is the brown star?',),
        ('Which is the brown rectangle?',),
        ('Which is the brown triangle?',),
        ('Which is the brown oval?',),
        ('Which is the brown pentagon?',),
        ('Which is the brown hexagon?',),
        ('Which is the brown rhombus?',),
        ('Which is the brown semicircle?',)
    ]

    cursor.executemany('INSERT INTO questions (question) VALUES (?)', questions)

    cursor.execute('SELECT id FROM questions')
    question_ids = cursor.fetchall()

    question_map = {idx + 1: qid[0] for idx, qid in enumerate(question_ids)}

    answers = [
        (1, 'static/semicircle/redsemicircle.png', 0),
        (1, 'static/circle/greencircle.png', 0),
        (1, 'static/circle/redcircle.png', 1),
        (2, 'static/circle/orangecircle.png', 0),
        (2, 'static/heart/redheart.png', 1),
        (2, 'static/triangle/blacktriangle.png', 0),
        (3, 'static/semicircle/redsemicircle.png', 1),
        (3, 'static/semicircle/pinksemicircle.png', 0),
        (3, 'static/oval/greenoval.png', 0),
        (4, 'static/hexagon/redhexagon.png', 0),
        (4, 'static/diamond/reddiamond.png', 1),
        (4, 'static/square/pinksquare.png', 0),
        (5, 'static/square/redsquare.png', 1),
        (5, 'static/pentagon/blackpentagon.png', 0),
        (5, 'static/rectangle/redrectangle.png', 0),
        (6, 'static/square/greensquare.png', 0),
        (6, 'static/rhombus/grayrhombus.png', 0),
        (6, 'static/star/redstar.png', 1),
        (7, 'static/square/pinksquare.png', 0),
        (7, 'static/rectangle/redrectangle.png', 1),
        (7, 'static/triangle/redtriangle.png', 0),
        (8, 'static/triangle/redtriangle.png', 1),
        (8, 'static/circle/greencircle.png', 0),
        (8, 'static/pentagon/orangepentagon.png', 0),
        (9, 'static/hexagon/redhexagon.png', 0),
        (9, 'static/oval/redoval.png', 1),
        (9, 'static/semicircle/purplesemicircle.png', 0),
        (10, 'static/pentagon/redpentagon.png', 1),
        (10, 'static/triangle/redtriangle.png', 0),
        (10, 'static/pentagon/greenpentagon.png', 0),
        (11, 'static/rhombus/orangerhombus.png', 0),
        (11, 'static/hexagon/redhexagon.png', 1),
        (11, 'static/square/redsquare.png', 0),
        (12, 'static/square/redsquare.png', 0),
        (12, 'static/circle/bluecircle.png', 0),
        (12, 'static/rhombus/redrhombus.png', 1),
        (13, 'static/heart/blueheart.png', 1),
        (13, 'static/circle/bluecircle.png', 0),
        (13, 'static/heart/redheart.png', 0),
        (14, 'static/diamond/bluediamond.png', 0),
        (14, 'static/circle/bluecircle.png', 1),
        (14, 'static/circle/yellowcircle.png', 0),
        (15, 'static/triangle/whitetriangle.png', 0),
        (15, 'static/rectangle/bluerectangle.png', 0),
        (15, 'static/diamond/bluediamond.png', 1),
        (16, 'static/rectangle/blackrectangle.png', 0),
        (16, 'static/square/bluesquare.png', 1),
        (16, 'static/triangle/bluetriangle.png', 0),
        (17, 'static/star/bluestar.png', 1),
        (17, 'static/square/bluesquare.png', 0),
        (17, 'static/star/purplestar.png', 0),
        (18, 'static/hexagon/bluehexagon.png', 0),
        (18, 'static/rectangle/bluerectangle.png', 1),
        (18, 'static/square/pinksquare.png', 0),
        (19, 'static/triangle/bluetriangle.png', 1),
        (19, 'static/pentagon/blackpentagon.png', 0),
        (19, 'static/rectangle/bluerectangle.png', 0),
        (20, 'static/circle/greencircle.png', 0),
        (20, 'static/rhombus/bluerhombus.png', 0),
        (20, 'static/oval/blueoval.png', 1),
        (21, 'static/square/bluesquare.png', 0),
        (21, 'static/pentagon/bluepentagon.png', 1),
        (21, 'static/triangle/browntriangle.png', 0),
        (22, 'static/hexagon/bluehexagon.png', 1),
        (22, 'static/circle/bluecircle.png', 0),
        (22, 'static/hexagon/blackhexagon.png', 0),
        (23, 'static/hexagon/bluehexagon.png', 0),
        (23, 'static/rhombus/bluerhombus.png', 1),
        (23, 'static/rhombus/purplerhombus.png', 0),
        (24, 'static/semicircle/bluesemicircle.png', 1),
        (24, 'static/circle/greencircle.png', 0),
        (24, 'static/pentagon/bluepentagon.png', 0),
        (25, 'static/star/yellowstar.png', 0),
        (25, 'static/heart/grayheart.png', 1),
        (25, 'static/heart/whiteheart.png', 0),
        (26, 'static/square/orangesquare.png', 0),
        (26, 'static/circle/bluecircle.png', 0),
        (26, 'static/circle/graycircle.png', 1),
        (27, 'static/diamond/graydiamond.png', 1),
        (27, 'static/triangle/blacktriangle.png', 0),
        (27, 'static/heart/grayheart.png', 0),
        (28, 'static/diamond/graydiamond.png', 0),
        (28, 'static/square/graysquare.png', 1),
        (28, 'static/circle/yellowcircle.png', 0),
        (29, 'static/star/graystar.png', 1),
        (29, 'static/triangle/blacktriangle.png', 0),
        (29, 'static/pentagon/graypentagon.png', 0),
        (30, 'static/rhombus/orangerhombus.png', 0),
        (30, 'static/rectangle/grayrectangle.png', 1),
        (30, 'static/square/graysquare.png', 0),
        (31, 'static/square/yellowsquare.png', 0),
        (31, 'static/circle/graycircle.png', 0),
        (31, 'static/triangle/graytriangle.png', 1),
        (32, 'static/oval/grayoval.png', 1),
        (32, 'static/circle/pinkcircle.png', 0),
        (32, 'static/heart/whiteheart.png', 0),
        (33, 'static/diamond/graydiamond.png', 0),
        (33, 'static/pentagon/graypentagon.png', 1),
        (33, 'static/circle/bluecircle.png', 0),
        (34, 'static/triangle/whitetriangle.png', 0),
        (34, 'static/rectangle/bluerectangle.png', 0),
        (34, 'static/hexagon/grayhexagon.png', 1),
        (35, 'static/rectangle/blackrectangle.png', 0),
        (35, 'static/rhombus/grayrhombus.png', 1),
        (35, 'static/triangle/bluetriangle.png', 0),
        (36, 'static/semicircle/graysemicircle.png', 1),
        (36, 'static/circle/bluecircle.png', 0),
        (36, 'static/star/graystar.png', 0),
        (37, 'static/heart/purpleheart.png', 0),
        (37, 'static/heart/pinkheart.png', 1),
        (37, 'static/square/pinksquare.png', 0),
        (38, 'static/circle/pinkcircle.png', 1),
        (38, 'static/pentagon/pinkpentagon.png', 0),
        (38, 'static/circle/bluecircle.png', 0),
        (39, 'static/triangle/whitetriangle.png', 0),
        (39, 'static/rhombus/bluerhombus.png', 0),
        (39, 'static/diamond/pinkdiamond.png', 1),
        (40, 'static/square/bluesquare.png', 0),
        (40, 'static/square/pinksquare.png', 1),
        (40, 'static/triangle/browntriangle.png', 0),
        (41, 'static/star/pinkstar.png', 1),
        (41, 'static/heart/blueheart.png', 0),
        (41, 'static/hexagon/pinkhexagon.png', 0),
        (42, 'static/hexagon/bluehexagon.png', 0),
        (42, 'static/rectangle/pinkrectangle.png', 1),
        (42, 'static/rhombus/purplerhombus.png', 0),
        (43, 'static/triangle/pinktriangle.png', 1),
        (43, 'static/diamond/yellowdiamond.png', 0),
        (43, 'static/pentagon/bluepentagon.png', 0),
        (44, 'static/circle/pinkcircle.png', 0),
        (44, 'static/oval/pinkoval.png', 1),
        (44, 'static/heart/brownheart.png', 0),
        (45, 'static/square/orangesquare.png', 0),
        (45, 'static/pentagon/redpentagon.png', 0),
        (45, 'static/pentagon/pinkpentagon.png', 1),
        (46, 'static/hexagon/pinkhexagon.png', 1),
        (46, 'static/triangle/blacktriangle.png', 0),
        (46, 'static/pentagon/redpentagon.png', 0),
        (47, 'static/diamond/graydiamond.png', 0),
        (47, 'static/rhombus/pinkrhombus.png', 1),
        (47, 'static/circle/pinkcircle.png', 0),
        (48, 'static/semicircle/pinksemicircle.png', 1),
        (48, 'static/triangle/redtriangle.png', 0),
        (48, 'static/semicircle/greensemicircle.png', 0),
        (49, 'static/rhombus/grayrhombus.png', 0),
        (49, 'static/heart/whiteheart.png', 1),
        (49, 'static/circle/redcircle.png', 0),
        (50, 'static/square/blacksquare.png', 0),
        (50, 'static/circle/bluecircle.png', 0),
        (50, 'static/circle/whitecircle.png', 1),
        (51, 'static/diamond/whitediamond.png', 1),
        (51, 'static/rhombus/bluerhombus.png', 0),
        (51, 'static/heart/grayheart.png', 0),
        (52, 'static/diamond/bluediamond.png', 0),
        (52, 'static/square/whitesquare.png', 1),
        (52, 'static/circle/yellowcircle.png', 0),
        (53, 'static/triangle/whitetriangle.png', 0),
        (53, 'static/rectangle/bluerectangle.png', 0),
        (53, 'static/star/whitestar.png', 1),
        (54, 'static/rectangle/blackrectangle.png', 0),
        (54, 'static/rectangle/whiterectangle.png', 1),
        (54, 'static/triangle/bluetriangle.png', 0),
        (55, 'static/triangle/whitetriangle.png', 1),
        (55, 'static/square/graysquare.png', 0),
        (55, 'static/star/purplestar.png', 0),
        (56, 'static/hexagon/grayhexagon.png', 0),
        (56, 'static/oval/whiteoval.png', 1),
        (56, 'static/oval/pinkoval.png', 0),
        (57, 'static/pentagon/whitepentagon.png', 1),
        (57, 'static/pentagon/blackpentagon.png', 0),
        (57, 'static/rectangle/orangerectangle.png', 0),
        (58, 'static/triangle/greentriangle.png', 0),
        (58, 'static/rhombus/bluerhombus.png', 0),
        (58, 'static/hexagon/whitehexagon.png', 1),
        (59, 'static/square/bluesquare.png', 0),
        (59, 'static/rhombus/whiterhombus.png', 1),
        (59, 'static/triangle/graytriangle.png', 0),
        (60, 'static/semicircle/whitesemicircle.png', 1),
        (60, 'static/circle/bluecircle.png', 0),
        (60, 'static/semicircle/blacksemicircle.png', 0),
        (61, 'static/heart/blueheart.png', 0),
        (61, 'static/heart/yellowheart.png', 1),
        (61, 'static/rhombus/purplerhombus.png', 0),
        (62, 'static/circle/yellowcircle.png', 1),
        (62, 'static/circle/greencircle.png', 0),
        (62, 'static/pentagon/brownpentagon.png', 0),
        (63, 'static/star/yellowstar.png', 0),
        (63, 'static/diamond/yellowdiamond.png', 1),
        (63, 'static/diamond/greendiamond.png', 0),
        (64, 'static/square/orangesquare.png', 0),
        (64, 'static/circle/bluecircle.png', 0),
        (64, 'static/square/yellowsquare.png', 1),
        (65, 'static/star/yellowstar.png', 1),
        (65, 'static/triangle/blacktriangle.png', 0),
        (65, 'static/diamond/orangediamond.png', 0),
        (66, 'static/rectangle/purplerectangle.png', 0),
        (66, 'static/rectangle/yellowrectangle.png', 1),
        (66, 'static/rhombus/yellowrhombus.png', 0),
        (67, 'static/triangle/yellowtriangle.png', 1),
        (67, 'static/triangle/blacktriangle.png', 0),
        (67, 'static/star/yellowstar.png', 0),
        (68, 'static/semicircle/orangesemicircle.png', 0),
        (68, 'static/oval/yellowoval.png', 1),
        (68, 'static/oval/redoval.png', 0),
        (69, 'static/square/yellowsquare.png', 0),
        (69, 'static/pentagon/greenpentagon.png', 0),
        (69, 'static/pentagon/yellowpentagon.png', 1),
        (70, 'static/hexagon/yellowhexagon.png', 1),
        (70, 'static/hexagon/pinkhexagon.png', 0),
        (70, 'static/heart/whiteheart.png', 0),
        (71, 'static/diamond/graydiamond.png', 0),
        (71, 'static/rhombus/yellowrhombus.png', 1),
        (71, 'static/star/bluestar.png', 0),
        (72, 'static/oval/whiteoval.png', 0),
        (72, 'static/semicircle/brownsemicircle.png', 0),
        (72, 'static/semicircle/yellowsemicircle.png', 1),
        (73, 'static/heart/blackheart.png', 0),
        (73, 'static/heart/greenheart.png', 1),
        (73, 'static/triangle/bluetriangle.png', 0),
        (74, 'static/circle/greencircle.png', 1),
        (74, 'static/circle/bluecircle.png', 0),
        (74, 'static/star/graystar.png', 0),
        (75, 'static/rhombus/orangerhombus.png', 0),
        (75, 'static/diamond/greendiamond.png', 1),
        (75, 'static/square/pinksquare.png', 0),
        (76, 'static/square/greensquare.png', 1),
        (76, 'static/pentagon/greenpentagon.png', 0),
        (76, 'static/square/bluesquare.png', 0),
        (77, 'static/triangle/yellowtriangle.png', 0),
        (77, 'static/rhombus/bluerhombus.png', 0),
        (77, 'static/star/greenstar.png', 1),
        (78, 'static/square/greensquare.png', 0),
        (78, 'static/rectangle/greenrectangle.png', 1),
        (78, 'static/rectangle/brownrectangle.png', 0),
        (79, 'static/triangle/greentriangle.png', 1),
        (79, 'static/heart/blueheart.png', 0),
        (79, 'static/hexagon/greenhexagon.png', 0),
        (80, 'static/hexagon/bluehexagon.png', 0),
        (80, 'static/oval/greenoval.png', 1),
        (80, 'static/circle/greencircle.png', 0),
        (81, 'static/pentagon/greenpentagon.png', 1),
        (81, 'static/diamond/yellowdiamond.png', 0),
        (81, 'static/pentagon/bluepentagon.png', 0),
        (82, 'static/circle/greencircle.png', 0),
        (82, 'static/hexagon/greenhexagon.png', 1),
        (82, 'static/heart/brownheart.png', 0),
        (83, 'static/square/orangesquare.png', 0),
        (83, 'static/pentagon/redpentagon.png', 0),
        (83, 'static/rhombus/greenrhombus.png', 1),
        (84, 'static/semicircle/greensemicircle.png', 1),
        (84, 'static/semicircle/blacksemicircle.png', 0),
        (84, 'static/oval/greenoval.png', 0),
        (85, 'static/diamond/orangediamond.png', 0),
        (85, 'static/heart/orangeheart.png', 1),
        (85, 'static/heart/pinkheart.png', 0),
        (86, 'static/star/yellowstar.png', 0),
        (86, 'static/circle/orangecircle.png', 1),
        (86, 'static/semicircle/orangesemicircle.png', 0),
        (87, 'static/square/orangesquare.png', 0),
        (87, 'static/circle/bluecircle.png', 0),
        (87, 'static/diamond/orangediamond.png', 1),
        (88, 'static/square/orangesquare.png', 1),
        (88, 'static/triangle/blacktriangle.png', 0),
        (88, 'static/diamond/orangediamond.png', 0),
        (89, 'static/star/redstar.png', 0),
        (89, 'static/star/orangestar.png', 1),
        (89, 'static/rhombus/yellowrhombus.png', 0),
        (90, 'static/rectangle/orangerectangle.png', 1),
        (90, 'static/triangle/blacktriangle.png', 0),
        (90, 'static/square/yellowsquare.png', 0),
        (91, 'static/triangle/browntriangle.png', 0),
        (91, 'static/triangle/orangetriangle.png', 1),
        (91, 'static/diamond/reddiamond.png', 0),
        (92, 'static/oval/yellowoval.png', 0),
        (92, 'static/circle/greencircle.png', 0),
        (92, 'static/oval/orangeoval.png', 1),
        (93, 'static/pentagon/orangepentagon.png', 1),
        (93, 'static/hexagon/pinkhexagon.png', 0),
        (93, 'static/triangle/whitetriangle.png', 0),
        (94, 'static/diamond/orangediamond.png', 0),
        (94, 'static/hexagon/orangehexagon.png', 1),
        (94, 'static/star/bluestar.png', 0),
        (95, 'static/triangle/orangetriangle.png', 0),
        (95, 'static/rhombus/brownrhombus.png', 0),
        (95, 'static/rhombus/orangerhombus.png', 1),
        (96, 'static/heart/orangeheart.png', 0),
        (96, 'static/semicircle/orangesemicircle.png', 1),
        (96, 'static/circle/blackcircle.png', 0),
        (97, 'static/heart/purpleheart.png', 1),
        (97, 'static/heart/blueheart.png', 0),
        (97, 'static/star/purplestar.png', 0),
        (98, 'static/rhombus/purplerhombus.png', 0),
        (98, 'static/circle/purplecircle.png', 1),
        (98, 'static/circle/pinkcircle.png', 0),
        (99, 'static/diamond/purplediamond.png', 1),
        (99, 'static/pentagon/greenpentagon.png', 0),
        (99, 'static/square/bluesquare.png', 0),
        (100, 'static/square/brownsquare.png', 0),
        (100, 'static/rhombus/purplerhombus.png', 0),
        (100, 'static/square/purplesquare.png', 1),
        (101, 'static/square/greensquare.png', 0),
        (101, 'static/star/purplestar.png', 1),
        (101, 'static/star/bluestar.png', 0),
        (102, 'static/rectangle/purplerectangle.png', 1),
        (102, 'static/square/bluesquare.png', 0),
        (102, 'static/rectangle/greenrectangle.png', 0),
        (103, 'static/hexagon/bluehexagon.png', 0),
        (103, 'static/triangle/purpletriangle.png', 1),
        (103, 'static/triangle/blacktriangle.png', 0),
        (104, 'static/oval/purpleoval.png', 1),
        (104, 'static/diamond/yellowdiamond.png', 0),
        (104, 'static/circle/purplecircle.png', 0),
        (105, 'static/hexagon/blackhexagon.png', 0),
        (105, 'static/pentagon/purplepentagon.png', 1),
        (105, 'static/heart/brownheart.png', 0),
        (106, 'static/square/purplesquare.png', 0),
        (106, 'static/pentagon/redpentagon.png', 0),
        (106, 'static/hexagon/purplehexagon.png', 1),
        (107, 'static/rhombus/purplerhombus.png', 1),
        (107, 'static/rhombus/blackrhombus.png', 0),
        (107, 'static/rhombus/greenrhombus.png', 0),
        (108, 'static/semicircle/orangesemicircle.png', 0),
        (108, 'static/semicircle/purplesemicircle.png', 1),
        (108, 'static/heart/pinkheart.png', 0),
        (109, 'static/heart/grayheart.png', 0),
        (109, 'static/rhombus/purplerhombus.png', 0),
        (109, 'static/heart/blackheart.png', 1),
        (110, 'static/oval/greenoval.png', 0),
        (110, 'static/circle/blackcircle.png', 1),
        (110, 'static/semicircle/blacksemicircle.png', 0),
        (111, 'static/diamond/blackdiamond.png', 1),
        (111, 'static/square/graysquare.png', 0),
        (111, 'static/rectangle/greenrectangle.png', 0),
        (112, 'static/hexagon/bluehexagon.png', 0),
        (112, 'static/square/blacksquare.png', 1),
        (112, 'static/triangle/blacktriangle.png', 0),
        (113, 'static/star/blackstar.png', 1),
        (113, 'static/diamond/graydiamond.png', 0),
        (113, 'static/star/purplestar.png', 0),
        (114, 'static/hexagon/blackhexagon.png', 0),
        (114, 'static/rectangle/blackrectangle.png', 1),
        (114, 'static/square/brownsquare.png', 0),
        (115, 'static/square/purplesquare.png', 0),
        (115, 'static/pentagon/graypentagon.png', 0),
        (115, 'static/triangle/blacktriangle.png', 1),
        (116, 'static/oval/blackoval.png', 1),
        (116, 'static/rhombus/blackrhombus.png', 0),
        (116, 'static/oval/blueoval.png', 0),
        (117, 'static/hexagon/grayhexagon.png', 0),
        (117, 'static/pentagon/blackpentagon.png', 1),
        (117, 'static/heart/blackheart.png', 0),
        (118, 'static/hexagon/greenhexagon.png', 0),
        (118, 'static/hexagon/blackhexagon.png', 1),
        (118, 'static/semicircle/blacksemicircle.png', 0),
        (119, 'static/rhombus/blackrhombus.png', 1),
        (119, 'static/square/graysquare.png', 0),
        (119, 'static/rectangle/redrectangle.png', 0),
        (120, 'static/circle/bluecircle.png', 0),
        (120, 'static/semicircle/blacksemicircle.png', 1),
        (120, 'static/semicircle/whitesemicircle.png', 0),
        (121, 'static/heart/brownheart.png', 1),
        (121, 'static/diamond/browndiamond.png', 0),
        (121, 'static/heart/purpleheart.png', 0),
        (122, 'static/circle/blackcircle.png', 0),
        (122, 'static/circle/browncircle.png', 1),
        (122, 'static/square/brownsquare.png', 0),
        (123, 'static/square/brownsquare.png', 0),
        (123, 'static/pentagon/graypentagon.png', 0),
        (123, 'static/diamond/browndiamond.png', 1),
        (124, 'static/square/brownsquare.png', 1),
        (124, 'static/rhombus/blackrhombus.png', 0),
        (124, 'static/square/orangesquare.png', 0),
        (125, 'static/hexagon/grayhexagon.png', 0),
        (125, 'static/star/brownstar.png', 1),
        (125, 'static/star/pinkstar.png', 0),
        (126, 'static/square/bluesquare.png', 0),
        (126, 'static/rectangle/brownrectangle.png', 1),
        (126, 'static/rectangle/grayrectangle.png', 0),
        (127, 'static/triangle/browntriangle.png', 1),
        (127, 'static/diamond/browndiamond.png', 0),
        (127, 'static/heart/whiteheart.png', 0),
        (128, 'static/circle/blackcircle.png', 0),
        (128, 'static/oval/brownoval.png', 1),
        (128, 'static/square/brownsquare.png', 0),
        (129, 'static/square/brownsquare.png', 0),
        (129, 'static/pentagon/graypentagon.png', 0),
        (129, 'static/pentagon/brownpentagon.png', 1),
        (130, 'static/hexagon/brownhexagon.png', 1),
        (130, 'static/rhombus/blackrhombus.png', 0),
        (130, 'static/pentagon/orangepentagon.png', 0),
        (131, 'static/hexagon/grayhexagon.png', 0),
        (131, 'static/rhombus/brownrhombus.png', 1),
        (131, 'static/star/brownstar.png', 0),
        (131, 'static/circle/graycircle.png', 0),
        (131, 'static/semicircle/brownsemicircle.png', 1),
        (131, 'static/semicircle/pinksemicircle.png', 0)
    ]

    cursor.executemany('INSERT INTO answers (question_id, image_path, is_correct) VALUES (?, ?, ?)', answers)

    conn.commit()
    conn.close()
    print("Data inserted successfully!")

if __name__ == '__main__':
    insert_data()
